/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as AuthIndexRouteImport } from "./routes/_auth/index"
import { Route as AuthUsageRouteImport } from "./routes/_auth/usage"
import { Route as AuthQuotasRouteImport } from "./routes/_auth/quotas"
import { Route as AuthWhatsappAccountsIndexRouteImport } from "./routes/_auth/whatsapp-accounts/index"
import { Route as AuthAiConfigsIndexRouteImport } from "./routes/_auth/ai-configs/index"
import { Route as AuthWhatsappAccountsNewRouteImport } from "./routes/_auth/whatsapp-accounts/new"
import { Route as AuthWhatsappAccountsAccountIdRouteImport } from "./routes/_auth/whatsapp-accounts/$accountId"
import { Route as AuthAiConfigsNewRouteImport } from "./routes/_auth/ai-configs/new"
import { Route as AuthAiConfigsConfigIdRouteImport } from "./routes/_auth/ai-configs/$configId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsageRoute = AuthUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuotasRoute = AuthQuotasRouteImport.update({
  id: "/quotas",
  path: "/quotas",
  getParentRoute: () => AuthRoute,
} as any)
const AuthWhatsappAccountsIndexRoute =
  AuthWhatsappAccountsIndexRouteImport.update({
    id: "/whatsapp-accounts/",
    path: "/whatsapp-accounts/",
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAiConfigsIndexRoute = AuthAiConfigsIndexRouteImport.update({
  id: "/ai-configs/",
  path: "/ai-configs/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthWhatsappAccountsNewRoute = AuthWhatsappAccountsNewRouteImport.update({
  id: "/whatsapp-accounts/new",
  path: "/whatsapp-accounts/new",
  getParentRoute: () => AuthRoute,
} as any)
const AuthWhatsappAccountsAccountIdRoute =
  AuthWhatsappAccountsAccountIdRouteImport.update({
    id: "/whatsapp-accounts/$accountId",
    path: "/whatsapp-accounts/$accountId",
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAiConfigsNewRoute = AuthAiConfigsNewRouteImport.update({
  id: "/ai-configs/new",
  path: "/ai-configs/new",
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiConfigsConfigIdRoute = AuthAiConfigsConfigIdRouteImport.update({
  id: "/ai-configs/$configId",
  path: "/ai-configs/$configId",
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthIndexRoute
  "/login": typeof LoginRoute
  "/quotas": typeof AuthQuotasRoute
  "/usage": typeof AuthUsageRoute
  "/ai-configs/$configId": typeof AuthAiConfigsConfigIdRoute
  "/ai-configs/new": typeof AuthAiConfigsNewRoute
  "/whatsapp-accounts/$accountId": typeof AuthWhatsappAccountsAccountIdRoute
  "/whatsapp-accounts/new": typeof AuthWhatsappAccountsNewRoute
  "/ai-configs/": typeof AuthAiConfigsIndexRoute
  "/whatsapp-accounts/": typeof AuthWhatsappAccountsIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/quotas": typeof AuthQuotasRoute
  "/usage": typeof AuthUsageRoute
  "/": typeof AuthIndexRoute
  "/ai-configs/$configId": typeof AuthAiConfigsConfigIdRoute
  "/ai-configs/new": typeof AuthAiConfigsNewRoute
  "/whatsapp-accounts/$accountId": typeof AuthWhatsappAccountsAccountIdRoute
  "/whatsapp-accounts/new": typeof AuthWhatsappAccountsNewRoute
  "/ai-configs": typeof AuthAiConfigsIndexRoute
  "/whatsapp-accounts": typeof AuthWhatsappAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/login": typeof LoginRoute
  "/_auth/quotas": typeof AuthQuotasRoute
  "/_auth/usage": typeof AuthUsageRoute
  "/_auth/": typeof AuthIndexRoute
  "/_auth/ai-configs/$configId": typeof AuthAiConfigsConfigIdRoute
  "/_auth/ai-configs/new": typeof AuthAiConfigsNewRoute
  "/_auth/whatsapp-accounts/$accountId": typeof AuthWhatsappAccountsAccountIdRoute
  "/_auth/whatsapp-accounts/new": typeof AuthWhatsappAccountsNewRoute
  "/_auth/ai-configs/": typeof AuthAiConfigsIndexRoute
  "/_auth/whatsapp-accounts/": typeof AuthWhatsappAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/quotas"
    | "/usage"
    | "/ai-configs/$configId"
    | "/ai-configs/new"
    | "/whatsapp-accounts/$accountId"
    | "/whatsapp-accounts/new"
    | "/ai-configs/"
    | "/whatsapp-accounts/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/quotas"
    | "/usage"
    | "/"
    | "/ai-configs/$configId"
    | "/ai-configs/new"
    | "/whatsapp-accounts/$accountId"
    | "/whatsapp-accounts/new"
    | "/ai-configs"
    | "/whatsapp-accounts"
  id:
    | "__root__"
    | "/_auth"
    | "/login"
    | "/_auth/quotas"
    | "/_auth/usage"
    | "/_auth/"
    | "/_auth/ai-configs/$configId"
    | "/_auth/ai-configs/new"
    | "/_auth/whatsapp-accounts/$accountId"
    | "/_auth/whatsapp-accounts/new"
    | "/_auth/ai-configs/"
    | "/_auth/whatsapp-accounts/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/": {
      id: "/_auth/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/usage": {
      id: "/_auth/usage"
      path: "/usage"
      fullPath: "/usage"
      preLoaderRoute: typeof AuthUsageRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/quotas": {
      id: "/_auth/quotas"
      path: "/quotas"
      fullPath: "/quotas"
      preLoaderRoute: typeof AuthQuotasRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/whatsapp-accounts/": {
      id: "/_auth/whatsapp-accounts/"
      path: "/whatsapp-accounts"
      fullPath: "/whatsapp-accounts/"
      preLoaderRoute: typeof AuthWhatsappAccountsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/ai-configs/": {
      id: "/_auth/ai-configs/"
      path: "/ai-configs"
      fullPath: "/ai-configs/"
      preLoaderRoute: typeof AuthAiConfigsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/whatsapp-accounts/new": {
      id: "/_auth/whatsapp-accounts/new"
      path: "/whatsapp-accounts/new"
      fullPath: "/whatsapp-accounts/new"
      preLoaderRoute: typeof AuthWhatsappAccountsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/whatsapp-accounts/$accountId": {
      id: "/_auth/whatsapp-accounts/$accountId"
      path: "/whatsapp-accounts/$accountId"
      fullPath: "/whatsapp-accounts/$accountId"
      preLoaderRoute: typeof AuthWhatsappAccountsAccountIdRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/ai-configs/new": {
      id: "/_auth/ai-configs/new"
      path: "/ai-configs/new"
      fullPath: "/ai-configs/new"
      preLoaderRoute: typeof AuthAiConfigsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/ai-configs/$configId": {
      id: "/_auth/ai-configs/$configId"
      path: "/ai-configs/$configId"
      fullPath: "/ai-configs/$configId"
      preLoaderRoute: typeof AuthAiConfigsConfigIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthQuotasRoute: typeof AuthQuotasRoute
  AuthUsageRoute: typeof AuthUsageRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAiConfigsConfigIdRoute: typeof AuthAiConfigsConfigIdRoute
  AuthAiConfigsNewRoute: typeof AuthAiConfigsNewRoute
  AuthWhatsappAccountsAccountIdRoute: typeof AuthWhatsappAccountsAccountIdRoute
  AuthWhatsappAccountsNewRoute: typeof AuthWhatsappAccountsNewRoute
  AuthAiConfigsIndexRoute: typeof AuthAiConfigsIndexRoute
  AuthWhatsappAccountsIndexRoute: typeof AuthWhatsappAccountsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthQuotasRoute: AuthQuotasRoute,
  AuthUsageRoute: AuthUsageRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAiConfigsConfigIdRoute: AuthAiConfigsConfigIdRoute,
  AuthAiConfigsNewRoute: AuthAiConfigsNewRoute,
  AuthWhatsappAccountsAccountIdRoute: AuthWhatsappAccountsAccountIdRoute,
  AuthWhatsappAccountsNewRoute: AuthWhatsappAccountsNewRoute,
  AuthAiConfigsIndexRoute: AuthAiConfigsIndexRoute,
  AuthWhatsappAccountsIndexRoute: AuthWhatsappAccountsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
